= patterns-demos

This repo contains some examples of Design Patterns in Java; it was split off from my main 
https://github.com/IanDarwin/javasrc[javasrc repo] to keep the latter from becoming bottom-heavy.

== Readings

The original book that popularized Design Patterns - after they were in use for a decade in the CS community - is
https://www.amazon.com/dp/0201633612[Design Patterns: Elements of Reusable Software],
by Gamma, Helm, Johnson and Vlissides, known more concisely as the Gang of Four or even the GoF.

A less academic, more memorable read is O'Reilly's
https://www.amazon.ca/dp/0596007124[Head-First Design Patterns].

== My Writings

The OO chapter of my https://www.amazon.ca/dp/144933704X[Java Cookbook], 3rd edition.

Command Pattern, in Oracle's Java Magazine May/June 2018. http://www.javamagazine.mozaicreader.com/MayJune2018/Default/15/0#&pageSet=15

State Pattern, in Oracle's Java Magazine, July/August 2018. http://www.javamagazine.mozaicreader.com/JulyAugust2018#&pageSet=66

Visitor Pattern, in Oracle's Java Magazine, September/October 2018. 
http://www.javamagazine.mozaicreader.com/SeptemberOctober2018/Default/66/0

Decorator Pattern, in Oracle's Java Magazine, November/December 2018.
http://www.javamagazine.mozaicreader.com/NovemberDecember2018/Default/67/0
